ALTER TABLE users
    ADD COLUMN created_at DATETIME NOT NULL DEFAULT NOW() COMMENT '생성일',
    ADD COLUMN updated_at DATETIME NOT NULL DEFAULT NOW() ON UPDATE NOW() COMMENT '수정일',
    ADD COLUMN deleted_at DATETIME NULL COMMENT '삭제일';