spring:
  config:
    import: "classpath:application.properties"
  datasource:
    url: jdbc:mysql://localhost:3306/upbrella_dev?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=utf8
    username: root
    password: ${DEV_DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        show-sql: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"
  metrics:
    export:
      datadog:
        enabled: true
        api-key: ${DD_API_KEY}
        step: 30s
        application-key: ${DD_APP_KEY}
        host-tag: ${DD_HOST_TAG}
        uri: ${DD_URI}
