spring:
  config:
    import: "classpath:application.properties"
  datasource:
    url: ${PROD_DATABASE_URL}
    username: ${PROD_DATABASE_USERNAME}
    password: ${PROD_DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true
  redis:
    host: ${PROD_REDIS_HOST}
    port: ${PROD_REDIS_PORT}
    password: ${PROD_REDIS_PASSWORD}
    timeout: 60000
  session:
    store-type: redis
    timeout: 3600

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
