name: Upbrella PRODUCTION PR Test

on:
  pull_request:
    branches: [ "release-production" ]
permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Set application properties
        run: |
          touch src/main/resources/application.properties
          echo "${{ secrets.APPLICATION_PROPERTIES }}" > src/main/resources/application.properties
      - name: Test with Gradle
        run: |
          chmod +x gradlew
          ./gradlew --info test
